config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'songs#index'
  resources :songs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_many :facts
end

app/models/fact.rb
class Fact < ApplicationRecord
end

app/models/song.rb
class Song < ApplicationRecord
end

app/models/trivia.rb
class Trivia < ApplicationRecord

end

app/models/trivium.rb
class Trivium < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/facts_controller.rb
class FactsController < ApplicationController
	def index
	  	@fact = Fact.order("RANDOM()")
  	end

  	def create
  		@fact = Fact.create(fact_params)
  	if @fact.invalid?
    	flash[:error] = '<strong>Could not save</strong> the data you entered is invalid.'
  	end
  		redirect_to root_path
  	end

	private

  	def fact_params
    	params.require(:fact).permit(:question, :answer)
  	end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  attr_reader :name, :artist, :genre
	def index
		@song = Song.order("RANDOM()").first
  end

  def new 
  	@song = Song.new
  end


  def create
    Song.create(song_params)
    redirect_to root_path
  end

  private

  def song_params
    params.require(:song).permit(:name, :artist, :genre)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
	attr_reader :name, :artist, :genre
	def index
		@song = Song.order("RANDOM()").first
  	end

  	def new 
  		@song = Song.new
  	end


  	def create
    	Song.create(song_params)
    	redirect_to root_path
  	end

  private

  def song_params
    params.require(:song).permit(:name, :artist, :genre)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/facts_helper.rb
module FactsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/facts/index.html.erb
<h1><%= @fact.question %></h1>
<h2><%= @fact.answer %></h2>

app/views/facts/new.html.erb
<div class='background'>
	<h1>Enter Your Fact</h1>
	<%= simple_form_for @fact do |f| %>
	  <%= f.input :question %>
	  <%= f.input :answer %>
	  <br />
	  <%= f.submit 'Submit', class: 'btn btn-danger' %>
	<% end %>
</div>

app/views/homepage/index.html.erb
<div class="booyah-box">
	<h1><%= @song.name %></h1><br />
	<h2><%= @song.artist %></h2><br />
	<h2><%= @song.genre %></h2><br />
</div>

app/views/homepage/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Song Details</h1>
  <%= simple_form_for @song do |f| %>
    <%= f.input :name %>
    <%= f.input :artist %>
    <%= f.input :genre %>
    <%= f.submit 'Create' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Katrina's Quizster App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" >Katrina's Song Finder App</a>
      <%= link_to 'Find a New Song', root_path, class: 'nav-link' %>
      <%= link_to 'Add a New Song', new_song_path, class: 'nav-link' %>
    </nav>
    </div>
      
    <%= yield %>
  </body>
</html>

app/views/songs/index.html.erb
<div class="booyah-box">
	<h1> Listen to this song next! </h1>
	<h2> Title: <%= @song.name %></h2><br />
	<h2> By: <%= @song.artist %></h2><br />
	<h2> Genre: <%= @song.genre %></h2><br />
</div>

app/views/songs/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Enter Your Song Details</h1>
  <%= simple_form_for @song do |f| %>
    <%= f.input :name %>
    <%= f.input :artist %>
    <%= f.input :genre %>
    <%= f.submit 'Create' %>
  <% end %>
</div>